baseurl = "/"
title = "Java vs GoLang"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "binario"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-115821533-2" # Enable Google Analytics by entering your tracking id

[Params]
  description = "Responsive card-based & code-light Hugo theme" # Site Description. Used in meta description
  copyright = "amarszalek.net" # Copyright holder, otherwise will use .Site.Title
  columns = 2 # Set the number of cards columns. Possible values: 1, 2, 3
  mainSections = ["post"] # Set main page sections
  post_meta = ["date"] # Enable post meta fields in given order
  dateFormat = "January 02, 2006" # Change the format of dates
  colorTheme = "dark-orange" # dark-green, dark-blue, dark-red, dark-violet
  customCSS = ["css/details.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files
  mainMenuAlignment = "left" # Align main menu (desktop version) to the right side
  hideNoPostsWarning = true # Don't show no posts empty state warning in main page, if true
  authorbox = true

[Author] # Used in authorbox
  name = "Adrian Marszałek"
  bio = true

[Params.Social]
  email = "contact@amarszalek.net"
  twitter = "a_mrszlk"
  linkedin = "adrianmarszalek"
  github = "adikm"

# Web App Manifest settings
# https://www.w3.org/TR/appmanifest/
# https://developers.google.com/web/fundamentals/web-app-manifest/
[Params.Manifest]
  name = "Java vs GoLang cheatsheet"
  shortName = "Java vs GoLang"
  display = "browser"
  startUrl = "/"
  backgroundColor = "#2a2a2a"
  themeColor = "#1b1b1b"
  description = "Java vs GoLang comparison cheatsheet"
  orientation = "portrait"
  scope = "/"

  [outputFormats]
  [outputFormats.MANIFEST]
    mediaType = "application/json"
    baseName = "manifest"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "MANIFEST"]